const Products = [
  {
    name: 'Airpods Bluetooth Headphones',
    image: 'airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
  {
    name: 'iPhone 11 Pro 256GB Memory',
    image: 'phone.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 100.99,
    countInStock: 7,
    rating: 4,
    numReviews: 8,
  },
  {
    name: 'Cannon EOS 80D DSLR Camera',
    image: 'camera.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 120.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    name: 'Sony Playstation 4 Pro White Version',
    image: 'playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 60.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    name: 'Logitech G-Series Gaming Mouse',
    image: 'mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3,
    numReviews: 10,
  },
  {
    name: 'Amazon Echo Dot 3rd Generation',
    image: 'alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    name: 'Amazon Echo Dot 2nd Generation',
    image: 'alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    name: 'Hatil Echo Frinedly 31st Generation',
    image: 'sofa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Hatil',
    category: 'Furniture',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    name: 'Regal Echo Frinedly 31st Generation',
    image: 'bedroom.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Regal',
    category: 'Furniture',
    price: 39.99,
    countInStock: 3,
    rating: 3,
    numReviews: 10,
  },
  {
    name: 'RFL Accessories',
    image: 'matress.webp',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'RFL',
    category: 'Accessories',
    price: 39.99,
    countInStock: 3,
    rating: 3,
    numReviews: 10,
  },
  {
    name: 'RFL Accessories',
    image: 'matress.webp',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'RFL',
    category: 'Accessories',
    price: 39.99,
    countInStock: 3,
    rating: 3,
    numReviews: 10,
  },
  {
    name: 'RFL Accessories',
    image: 'coffee-table.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'RFL',
    category: 'Accessories',
    price: 39.39,
    countInStock: 4,
    rating: 5,
    numReviews: 8,
  },
  {
    name: 'Gas Stove',
    image: 'gas-stove.jpg',
    description: 'pressure cooker for smart cooking',
    brand: 'Pran-RFL',
    category: 'HomeAppliance',
    price: 39.39,
    countInStock: 4,
    rating: 5,
    numReviews: 8,
  },
  {
    name: 'Knife',
    image: 'knife.jpg',
    description: 'pressure cooker for smart cooking',
    brand: 'RFL',
    category: 'KitchenWire',
    price: 58.39,
    countInStock: 2,
    rating: 1,
    numReviews: 80,
  },
]

export default Products
